# Site settings
baseurl = "/"
languageCode = "en-us"
title = "limosa"
theme = "hugo-cactus-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    name = "limosa"
    description = "A blog about math, programming and data science"
    bio = "A blog about math, programming and data science"
    enableRSS = false

    # Navigation links
    home = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

    iconFont = "mono-social"
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    github   = "https://www.github.com/basjacobs93"
    linkedin = "https://www.linkedin.com/in/basjacobs93"
