# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Bas Jacobs"
theme = "basjacobs-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

googleAnalytics = "UA-128252699-1"

[params]
    name = "Bas Jacobs"
    description = "My blog about math, programming and data science"
    bio = "My blog about math, programming and data science"
    enableRSS = true

    # Navigation links
    home = ""
    # Copyright
    copyright = ""
    # 404 page
    title404 = ""
    subtitle404 = ""
