# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Bas Jacobs"
theme = "basjacobs-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

googleAnalytics = "UA-128252699-1"

[params]
    name = "Bas Jacobs"
    description = "My blog about math, programming and data science"
    bio = "My blog about math, programming and data science"
    enableRSS = true

    # Navigation links
    home = ""
    # Copyright
    copyright = ""
    # 404 page
    title404 = ""
    subtitle404 = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
