# Site settings
baseurl = "/"
languageCode = "en-us"
title = "limosa"
theme = "limosa-theme"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    name = "limosa"
    description = "A blog about math, programming and data science"
    bio = "A blog about math, programming and data science"
    enableRSS = true

    # Navigation links
    home = ""
    # Copyright
    copyright = ""
    # 404 page
    title404 = ""
    subtitle404 = ""
